# Generated by Django 2.0.2 on 2018-04-09 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autores', to='evento.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=100)),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Avaliador', to='evento.Avaliador')),
                ('nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notas', to='evento.Nota')),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='avaliacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Avaliacoes', to='evento.Avaliacao'),
        ),
    ]
