# Generated by Django 2.0.2 on 2018-04-09 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20180409_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Artigos', to='evento.Autor')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autores', to='evento.Autor')),
            ],
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='autores',
        ),
    ]
