# Generated by Django 2.0.2 on 2018-04-10 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20180409_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AvaliacaoAv', to='evento.Avaliacao')),
                ('nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotasAv', to='evento.Nota')),
            ],
        ),
    ]
