# Generated by Django 2.0.2 on 2018-04-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_avaliacaonota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota',
        ),
    ]
